project:
  type: website

website:
  title: "Alzheimer's Diagnosis Prediction"
  navbar:
    left:
      - about.qmd
      - href: index.qmd
        text: Intro
      - model.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



